[algokit]
min_version = "v2.0.0"

[project]
type = "daemon"
name = 'randomness-beacon-daemon'

[project.run]
build = { commands = ['npm run build'], description = 'Build daemon' }
test = { commands = ['npm run test'], description = 'Run daemon tests' }
